# Generated by Django 5.1.6 on 2025-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('faculty', models.CharField(choices=[('Informatics & Computing', 'Informatics & Computing'), ('Engineering & Technology', 'Engineering & Technology'), ('Sciences', 'Sciences'), ('Life Sciences', 'Life Sciences'), ('Management', 'Management'), ('Languages & Media Studies', 'Languages & Media Studies'), ('CCSD', 'CCSD')], max_length=50)),
            ],
        ),
    ]
